[dev]
  command = "npm run dev"
  targetPort = 5173
  framework = "vite"
  publish = "frontend/dist"

[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  RPC_URL = "https://polygon-rpc.com"
  CONTRACT_ADDRESS = "0xD1398D1A81cC43d09AD30EfBF6c1aE76b621Ca2f"
  NFT_STORAGE_KEY = "20f46cc3.68e9b5f87400440e8f8dc14ce1331350"
  PRIVATE_KEY = "0x620d989cffce908bfa6e1b78a0ed298f67dd2b1342c2916a4a5cea5c2eb13d5d"
  TREASURY_ADDRESS = "0xe4DCDA425ED17D5439B83AfFBa6C91a509E36b84"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
